{% set version = "6.2.3" %}
{% set sha256 = "1e3bd58434c5d31f852ffd1af907a6485b5857966c770eac02fb0111720027cd" %}

package:
  name: ipyparallel
  version: {{ version }}

source:
  fn: ipyparallel-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/i/ipyparallel/ipyparallel-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1000
  entry_points:
    - ipcluster = ipyparallel.apps.ipclusterapp:launch_new_instance
    - ipcontroller = ipyparallel.apps.ipcontrollerapp:launch_new_instance
    - ipengine = ipyparallel.apps.ipengineapp:launch_new_instance
  script: pip install --no-deps --ignore-installed .


requirements:
  host:
    - python
    - pip

  run:
    - python
    - futures               # [py2k]
    - decorator
    - tornado >=4
    - python-dateutil >=2.1
    - pyzmq >=13
    - ipython_genutils
    - ipython >=4
    - jupyter_client
    - ipykernel

test:
  requires:
    - notebook >=5.3
  imports:
    - ipyparallel
    - ipyparallel.apps
    - ipyparallel.client
    - ipyparallel.controller
    - ipyparallel.engine
    - ipyparallel.serialize
  commands:
    - ipcluster -h
    - ipengine -h
    - ipcontroller -h

about:
  home: http://ipython.org
  license: BSD 3-Clause
  license_family: BSD
  summary: Interactive Parallel Computing with IPython

extra:
  recipe-maintainers:
    - jakirkham
    - minrk
