{% set version = "9.0.0" %}
{% set python_min = python_min | default("3.8") %}

package:
  name: ipyparallel
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/i/ipyparallel/ipyparallel-{{ version }}.tar.gz
  sha256: 70601cbaf9a169d350ffe22c82d5bbdfe6dfe4c4df02836d9990e9c559b5bcb6

build:
  number: 0
  noarch: python
  entry_points:
    - ipcluster = ipyparallel.cluster.app:main
    - ipcontroller = ipyparallel.controller.app:main
    - ipengine = ipyparallel.engine.app:main
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - hatchling >=0.25
    - pip
    - python {{ python_min }}.*
  run:
    - decorator
    - importlib-metadata >=3.6
    - ipykernel >=6.9.1
    - ipython >=5
    - jupyter_client >=7
    - psutil
    - python >={{ python_min }}
    - python-dateutil >=2.1
    - pyzmq >=25
    - tornado >=6.1
    - tqdm
    - traitlets >=5

test:
  requires:
    - m2-grep  # [win]
    - python ={{ python_min }}
    - jupyterlab ==4.*
    - nbclassic
    - pip
  imports:
    - ipyparallel
    - ipyparallel.apps
    - ipyparallel.client
    - ipyparallel.controller
    - ipyparallel.engine
    - ipyparallel.serialize
  commands:
    - pip check
    - ipcluster -h
    - ipengine -h
    - ipcontroller -h
    # list
    - jupyter labextension list
    - jupyter server extension list
    - jupyter nbclassic extension list
    # write
    - jupyter labextension list 1>labextensions 2>&1
    - jupyter server extension list 1>server_extensions 2>&1
    - jupyter nbclassic extension list 1>nbclassic_extensions 2>&1
    # validate
    - grep -iE "ipyparallel-labextension.*v{{ version.replace(".", "\\.") }}.*OK" labextensions
    - grep -iE "ipyparallel.*{{ version.replace(".", "\\.") }}.*OK" server_extensions
    - grep -iE "ipyparallel.*{{ version.replace(".", "\\.") }}.*OK" nbclassic_extensions

about:
  home: https://github.com/ipython/ipyparallel
  license: BSD-3-Clause
  license_file:
    - COPYING.md
    - ipyparallel/labextension/static/third-party-licenses.json
  license_family: BSD
  summary: Interactive Parallel Computing with IPython
  doc_url: https://ipyparallel.readthedocs.io
  dev_url: https://github.com/ipython/ipyparallel

extra:
  recipe-maintainers:
    - jakirkham
    - minrk
    - bollwyvl
