{% set version = "6.3.0" %}
{% set sha256 = "0a97b276c62db633e9e97a816282bdd166f9df74e28204f0c8fa54b71944cfdc" %}

package:
  name: ipyparallel
  version: {{ version }}

source:
  fn: ipyparallel-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/i/ipyparallel/ipyparallel-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  entry_points:
    - ipcluster = ipyparallel.apps.ipclusterapp:launch_new_instance
    - ipcontroller = ipyparallel.apps.ipcontrollerapp:launch_new_instance
    - ipengine = ipyparallel.apps.ipengineapp:launch_new_instance
  script: pip install --no-deps --ignore-installed .


requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip

  run:
    - python
    - futures               # [py2k]
    - decorator
    - tornado >=4
    - python-dateutil >=2.1
    - pyzmq >=13
    - ipython_genutils
    - ipython >=4
    - jupyter_client
    - ipykernel >=4.4

test:
  requires:
    - notebook >=5.3
  imports:
    - ipyparallel
    - ipyparallel.apps
    - ipyparallel.client
    - ipyparallel.controller
    - ipyparallel.engine
    - ipyparallel.serialize
  commands:
    - ipcluster -h
    - ipengine -h
    - ipcontroller -h

about:
  home: http://ipython.org
  license: BSD-3-Clause
  license_file: COPYING.md
  license_family: BSD
  summary: Interactive Parallel Computing with IPython

extra:
  recipe-maintainers:
    - jakirkham
    - minrk
