appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: default, linux_ppc64le: default}
travis:
  secure: {BINSTAR_TOKEN: mF3msLsRy1WJBPKWvMYIZLCSPOgdi+bUstMTchP2mFN5xL0UdEvx3Wqzd+yZOcy6pYc2lgt2CTHtupZNVW/KXybBg5yqrN9tWEmilooaS2/j+su8rOlSLFyoJtbiI0ZoBuzh7SBVywq7lDHa6FR8hq8wFCjVS/Tmz26QZE2u20wUGE3utiMCOISsV1ndibr3LkHBYN1K+tPOyNT3SkGz9qZGE06VVUp21pU3n2hQNAxWz9+y7ihT8FXA7O6Tq/ua09L48S6uE1qJ7keTt6w+4ksAT2SpDK8azyiydKJ6RaD64Luv2nIYr9BN5LYXC9Hl2uNBvcwDBAIsC98M2iyXwJyHNSKDB4Oy/BtPCGQkAH6syvSUqlexyW6IReJZnjD+xeU9Nkl4klSGxyrEib5nNFPyJdAjndBsX7Gym0LELBzIaDVMepEsjya3/lPFaAqZupKDFNxb6tH8Np08Yw3F3Ip5I1VJBqU1RerZfGCT+v0fLnyB21TSLvYasPTsYepLg38hVYdB4KKKMoQnOkU/ZAvqrSCyd4QuBpeNm6opOJ/lewsJNlUDrg5iSwG1KAF3Kk/Ebgm5RfCfgwvVjCkd7kq/N0PQXR4lzluZlXatkxxM39qCfVtoLoMF1Vm19cOp6ogw4RRbL77tta7qsxtHIGdD0BZ1u/X/5Jvzn8Q7f9o=}
